# _   _ _______  ___   _ ____  
#| \ | | ____\ \/ / | | / ___| 
#|  \| |  _|  \  /| | | \___ \ 
#| |\  | |___ /  \| |_| |___) |
#|_| \_|_____/_/\_\\___/|____/ 
#
# The powerhouse docker-compose configuration for all LordOfWizard's Services.

###################################################################################################

#       ____  _ _   _                            _   
#  __ _| __ )(_) |_| |_ ___  _ __ _ __ ___ _ __ | |_ 
# / _` |  _ \| | __| __/ _ \| '__| '__/ _ \ '_ \| __|
#| (_| | |_) | | |_| || (_) | |  | | |  __/ | | | |_ 
# \__, |____/|_|\__|\__\___/|_|  |_|  \___|_| |_|\__|
#    |_|                                             

---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=6901
      - TORRENTING_PORT=6881
    volumes:
      - ${PWD}/qbittorrent/config:/config
      - ${PWD}/qbittorrent/downloads:/downloads #optional
    ports:
      - 6901:6901
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

###################################################################################################

#                 __ _         
#  ___ _ __ __ _ / _| |_ _   _ 
# / __| '__/ _` | |_| __| | | |
#| (__| | | (_| |  _| |_| |_| |
# \___|_|  \__,_|_|  \__|\__, |
#                        |___/ 

  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "6902:8443"               # HTTPS
      - "8123:8123"               # DYNMAP
      - "19132:19132/udp"        # BEDROCK
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - ${PWD}/crafty/backups:/crafty/backups
      - ${PWD}/crafty/logs:/crafty/logs
      - ${PWD}/crafty/servers:/crafty/servers
      - ${PWD}/crafty/config:/crafty/app/config
      - ${PWD}/crafty/import:/crafty/import

###################################################################################################

#
#    _             _ _       ____              _     ____  _          _  __ 
#   / \  _   _  __| (_) ___ | __ )  ___   ___ | | __/ ___|| |__   ___| |/ _|
#  / _ \| | | |/ _` | |/ _ \|  _ \ / _ \ / _ \| |/ /\___ \| '_ \ / _ \ | |_ 
# / ___ \ |_| | (_| | | (_) | |_) | (_) | (_) |   <  ___) | | | |  __/ |  _|
#/_/   \_\__,_|\__,_|_|\___/|____/ \___/ \___/|_|\_\|____/|_| |_|\___|_|_|  
#                                                                          

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 6903:80
    volumes:
      - ${PWD}/audiobookshelf/audiobooks:/audiobooks
      - ${PWD}/audiobookshelf/podcasts:/podcasts
      - ${PWD}/audiobookshelf/config:/config
      - ${PWD}/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Asia/Kolkata

###################################################################################################


#  ____           _                 
# |  _ \ __ _  __| | __ _ _ __ _ __ 
# | |_) / _` |/ _` |/ _` | '__| '__|
# |  _ < (_| | (_| | (_| | |  | |   
# |_| \_\__,_|\__,_|\__,_|_|  |_|   
#                                   
#  ____                              
# / ___|  ___  _ __   __ _ _ __ _ __ 
# \___ \ / _ \| '_ \ / _` | '__| '__|
#  ___) | (_) | | | | (_| | |  | |   
# |____/ \___/|_| |_|\__,_|_|  |_|   
#                                    
# __        ___     _                          
# \ \      / / |__ (_)___ _ __   ___ _ __ _ __ 
#  \ \ /\ / /| '_ \| / __| '_ \ / _ \ '__| '__|
#   \ V  V / | | | | \__ \ |_) |  __/ |  | |   
#    \_/\_/  |_| |_|_|___/ .__/ \___|_|  |_|   
#                        |_|                   
#  ____                    _                 
# |  _ \ _ __ _____      _| | __ _ _ __ _ __ 
# | |_) | '__/ _ \ \ /\ / / |/ _` | '__| '__|
# |  __/| | | (_) \ V  V /| | (_| | |  | |   
# |_|   |_|  \___/ \_/\_/ |_|\__,_|_|  |_|   
#                                            
#  ____  _ _                   
# | __ )| (_)__________ _ _ __ 
# |  _ \| | |_  /_  / _` | '__|
# | |_) | | |/ / / / (_| | |   
# |____/|_|_/___/___\__,_|_|   
#                              





#  ____                   _   _     _             
# / ___| _   _ _ __   ___| |_| |__ (_)_ __   __ _ 
# \___ \| | | | '_ \ / __| __| '_ \| | '_ \ / _` |
#  ___) | |_| | | | | (__| |_| | | | | | | | (_| |
# |____/ \__, |_| |_|\___|\__|_| |_|_|_| |_|\__, |
#        |___/                              |___/ 
#

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${PWD}/syncthing/sync_folder:/var/syncthing
    ports:
      - 6904:8384 # Web UI
      - 22001:22000/tcp # TCP file transfers
      - 22001:22000/udp # QUIC file transfers
      - 21028:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

